upsample_fac: 2
base_resolution: 16
src_path: 'data/GT_sparse_tensors'

layers: 2
first_ks: 3
one_layers: 4
features: 128
# epochs: 20000
epochs: 100000

lr: 0.0001
batch_size: 10
clip_size: 20

dropout: 0.05
time_emb: 6
diffusion_timesteps: 1000
save_every: 500