upsample_fac: 2
base_resolution: 16
src_path: 'data/GT_sparse_tensors'

layers: 3
first_ks: 5
one_layers: 2
features: 128
epochs: 40000
lr: 0.0001
batch_size: 2
clip_size: 20

max_T: 300
dropout: 0.05
time_emb: 6
diffusion_timesteps: 1000
save_every: 500